site_name: Haiker技术博客
site_description: 你。认真。啦。技术博客
site_author: Haiker
site_url: https://ni.renzhen.la
repo_url: https://github.com/ihaiker/ni.renzhen.la
copyright: Copyright @2021 Haiker

theme:
  name: readthedocs
  navigation_depth: 1

extra_css:
  - extra.css
nav: 
  - '效果不错的HTML': template.md 
  - '主页': index.md 
  - '编程语言': language 
  - '云服务': cloud 
  - 'framework': framework 
  - 'knowledge': knowledge 
  - '管理工具': management 
  - '数据库': database 
  - '工具': tools 
  - '关于我们': about.md 
